export const captainFormConfig = {
  sections: [
    {
      id: "photo_upload",
      title: "Profile Photo",
      icon: "Camera",
      gradient: "from-indigo-500 to-purple-600",
      fields: [
        {
          name: "photoFile",
          label: "Profile Photo",
          type: "photo",
          placeholder: "",
          required: false,
          validation: "",
          gridCols: "col-span-full",
          helpText: "Upload a profile photo for the captain",
        },
      ],
    },
    {
      id: "login_credentials",
      title: "Login Credentials",
      icon: "Lock",
      gradient: "from-purple-500 to-indigo-600",
      fields: [
        {
          name: "email",
          label: "Email Address",
          type: "email",
          placeholder: "captain@example.com",
          required: true,
          validation: "email",
          gridCols: "md:col-span-1",
          icon: "Mail",
          helpText: "Used for captain login",
          maxLength: 50,
        },
        {
          name: "password",
          label: "Password",
          type: "password",
          placeholder: "Enter password",
          required: true,
          validation: "password",
          gridCols: "md:col-span-1",
          icon: "Lock",
          helpText: "Minimum 6 characters",
          maxLength: 50,
          conditionalRequired: true, // Required only for new captains
          editPlaceholder: "Enter new password (optional)",
          editHelpText: "Leave blank to keep current password",
        },
      ],
    },
    {
      id: "personal_info",
      title: "Personal Information",
      icon: "User",
      gradient: "from-blue-500 to-indigo-600",
      fields: [
        {
          name: "firstName",
          label: "First Name",
          type: "text",
          placeholder: "Enter first name",
          required: true,
          validation: "firstName",
          gridCols: "md:col-span-1",
          icon: "User",
          helpText: "Enter the captain's first name",
          maxLength: 30,
          autoFocus: true,
        },
        {
          name: "lastName",
          label: "Last Name",
          type: "text",
          placeholder: "Enter last name",
          required: true,
          validation: "lastName",
          gridCols: "md:col-span-1",
          icon: "User",
          helpText: "Enter the captain's last name",
          maxLength: 30,
        },
        {
          name: "mobileNo",
          label: "Mobile Number",
          type: "tel",
          placeholder: "9876543210",
          required: true,
          validation: "mobileNo",
          gridCols: "md:col-span-1",
          icon: "Phone",
          helpText: "10-digit mobile number",
          maxLength: 10,
        },
        {
          name: "experience",
          label: "Experience (Years)",
          type: "number",
          placeholder: "0",
          required: true,
          validation: "experience",
          gridCols: "md:col-span-1",
          icon: "Calendar",
          helpText: "Years of work experience",
          min: "0",
          max: "99",
        },
      ],
    },
    {
      id: "identification",
      title: "Identification Documents",
      icon: "CreditCard",
      gradient: "from-green-500 to-emerald-600",
      fields: [
        {
          name: "adharNo",
          label: "Aadhar Number",
          type: "text",
          placeholder: "123456789012",
          required: true,
          validation: "adharNo",
          gridCols: "md:col-span-1",
          icon: "CreditCard",
          helpText: "12-digit Aadhar number",
          maxLength: 12,
        },
        {
          name: "panNo",
          label: "PAN Number",
          type: "text",
          placeholder: "ABCDE1234F",
          required: true,
          validation: "panNo",
          gridCols: "md:col-span-1",
          icon: "CreditCard",
          helpText: "10-character PAN (e.g., ABCDE1234F)",
          maxLength: 10,
          transform: "uppercase",
        },
      ],
    },
    {
      id: "address_info",
      title: "Address Information",
      icon: "MapPin",
      gradient: "from-orange-500 to-red-600",
      fields: [
        {
          name: "address",
          label: "Address",
          type: "textarea",
          placeholder:
            "Enter complete address including city, state, and pincode",
          required: true,
          validation: "address",
          gridCols: "col-span-full",
          helpText: "Complete residential address",
          maxLength: 200,
          rows: 3,
        },
      ],
    },
  ],
};
