export const offersFormConfig = {
  sections: [
    {
      id: "basic_info",
      title: "Basic Information",
      icon: "Tag",
      gradient: "from-blue-500 to-indigo-600",
      fields: [
        {
          name: "offerName",
          label: "Offer Name",
          type: "text",
          placeholder: "Enter offer name",
          required: true,
          validation: "required",
          gridCols: "md:col-span-2",
          minLength: 3,
        },
        {
          name: "offerDescription",
          label: "Description",
          type: "textarea",
          placeholder: "Describe your offer...",
          required: false,
          validation: "",
          gridCols: "md:col-span-2",
          rows: 3,
        },
        {
          name: "offerType",
          label: "Offer Type",
          type: "select",
          placeholder: "Select offer type",
          required: true,
          validation: "required",
          gridCols: "md:col-span-1",
          options: [
            { value: "percentage", label: "Percentage Discount" },
            { value: "fixed", label: "Fixed Amount" },
            { value: "free_delivery", label: "Free Delivery" },
            { value: "buy_one_get_one", label: "Buy One Get One" },
          ],
        },
        {
          name: "discountValue",
          label: "Discount Value",
          type: "number",
          placeholder: "Enter discount value",
          required: true,
          validation: "discountValue",
          gridCols: "md:col-span-1",
          conditionalField: true,
          hideWhen: ["free_delivery", "buy_one_get_one"],
          step: "0.01",
          min: "0",
          dynamicProps: true, // This indicates the field props change based on offerType
        },
      ],
    },
    {
      id: "validity",
      title: "Validity Period",
      icon: "Calendar",
      gradient: "from-green-500 to-emerald-600",
      fields: [
        {
          name: "validFrom",
          label: "Valid From",
          type: "date",
          placeholder: "",
          required: true,
          validation: "validFrom",
          gridCols: "md:col-span-1",
        },
        {
          name: "validUntil",
          label: "Valid Until",
          type: "date",
          placeholder: "",
          required: true,
          validation: "validUntil",
          gridCols: "md:col-span-1",
        },
      ],
    },
    {
      id: "usage_limits",
      title: "Usage Limits",
      icon: "Users",
      gradient: "from-purple-500 to-pink-600",
      fields: [
        {
          name: "minimumOrderAmount",
          label: "Minimum Order Amount (₹)",
          type: "number",
          placeholder: "0",
          required: false,
          validation: "minimumOrder",
          gridCols: "md:col-span-1",
          step: "1",
          min: "0",
        },
        {
          name: "maxUsageCount",
          label: "Max Total Usage",
          type: "number",
          placeholder: "Unlimited",
          required: false,
          validation: "positiveNumber",
          gridCols: "md:col-span-1",
          step: "1",
          min: "1",
        },
        {
          name: "usagePerCustomer",
          label: "Usage Per Customer",
          type: "number",
          placeholder: "Unlimited",
          required: false,
          validation: "positiveNumber",
          gridCols: "md:col-span-1",
          step: "1",
          min: "1",
        },
      ],
    },
    {
      id: "additional_details",
      title: "Additional Details",
      icon: "FileText",
      gradient: "from-orange-500 to-red-600",
      fields: [
        {
          name: "offerCode",
          label: "Offer Code",
          type: "text",
          placeholder: "Auto-generated if empty",
          required: false,
          validation: "",
          gridCols: "md:col-span-1",
        },
        {
          name: "terms",
          label: "Terms & Conditions",
          type: "textarea",
          placeholder: "Enter terms and conditions...",
          required: false,
          validation: "",
          gridCols: "md:col-span-2",
          rows: 3,
        },
        {
          name: "isActive",
          label: "Make offer active",
          type: "checkbox",
          placeholder: "",
          required: false,
          validation: "",
          gridCols: "md:col-span-2",
          defaultValue: true,
        },
      ],
    },
  ],
};
