export const formConfig = {
  sections: [
    {
      id: "basic",
      title: "Basic Information",
      icon: "Building",
      gradient: "from-indigo-500 to-purple-600",
      fields: [
        {
          name: "businessName",
          label: "Business Name",
          type: "text",
          placeholder: "Enter your business name",
          required: true,
          validation: "businessName",
          gridCols: "lg:col-span-1",
        },
        {
          name: "businessType",
          label: "Business Type",
          type: "select",
          placeholder: "Select business type",
          required: true,
          validation: "required",
          options: [
            { value: "", label: "Select Business Type" },
            { value: "restaurant", label: "Restaurant" },
            { value: "cafe", label: "Cafe" },
            { value: "bakery", label: "Bakery" },
            { value: "bar_pub", label: "Bar & Pub" },
            { value: "fast_food", label: "Fast Food" },
            { value: "fine_dining", label: "Fine Dining" },
            { value: "food_truck", label: "Food Truck" },
            { value: "cloud_kitchen", label: "Cloud Kitchen" },
            { value: "catering", label: "Catering Service" },
            { value: "dessert_shop", label: "Dessert Shop" },
          ],
          gridCols: "lg:col-span-1",
        },
        {
          name: "cuisineTypes",
          label: "Cuisine Types",
          type: "multiselect",
          placeholder: "Select cuisine types",
          required: true,
          validation: "required",
          options: [
            { value: "indian", label: "Indian" },
            { value: "chinese", label: "Chinese" },
            { value: "italian", label: "Italian" },
            { value: "mexican", label: "Mexican" },
            { value: "thai", label: "Thai" },
            { value: "japanese", label: "Japanese" },
            { value: "american", label: "American" },
            { value: "continental", label: "Continental" },
            { value: "south_indian", label: "South Indian" },
            { value: "north_indian", label: "North Indian" },
            { value: "punjabi", label: "Punjabi" },
            { value: "gujarati", label: "Gujarati" },
            { value: "maharashtrian", label: "Maharashtrian" },
            { value: "bengali", label: "Bengali" },
            { value: "hyderabadi", label: "Hyderabadi" },
            { value: "mediterranean", label: "Mediterranean" },
            { value: "korean", label: "Korean" },
            { value: "lebanese", label: "Lebanese" },
          ],
          gridCols: "lg:col-span-2",
        },
        {
          name: "primaryContact",
          label: "Primary Contact Number",
          type: "tel",
          placeholder: "Enter 10-digit contact number",
          required: true,
          validation: "contact",
          maxLength: 10,
          gridCols: "lg:col-span-1",
        },
        {
          name: "alternateContact",
          label: "Alternate Contact Number",
          type: "tel",
          placeholder: "Enter alternate contact (optional)",
          required: false,
          validation: "contactOptional",
          maxLength: 10,
          gridCols: "lg:col-span-1",
        },
        {
          name: "description",
          label: "Business Description",
          type: "textarea",
          placeholder:
            "Describe your business, specialties, and unique features",
          required: false,
          validation: "",
          rows: 3,
          gridCols: "lg:col-span-2",
        },
      ],
    },
    {
      id: "location",
      title: "Location Information",
      icon: "MapPin",
      gradient: "from-emerald-500 to-teal-600",
      fields: [
        {
          name: "address",
          label: "Complete Address",
          type: "textarea",
          placeholder: "Enter complete business address",
          required: true,
          validation: "required",
          rows: 2,
          gridCols: "lg:col-span-2",
        },
        {
          name: "area",
          label: "Area/Locality",
          type: "text",
          placeholder: "Enter area or locality",
          required: true,
          validation: "required",
          gridCols: "lg:col-span-1",
        },
        {
          name: "landmark",
          label: "Landmark",
          type: "text",
          placeholder: "Enter nearby landmark",
          required: false,
          validation: "",
          gridCols: "lg:col-span-1",
        },
        {
          name: "city",
          label: "City",
          type: "text",
          placeholder: "Enter city",
          required: true,
          validation: "required",
          gridCols: "md:col-span-1",
        },
        {
          name: "district",
          label: "District",
          type: "text",
          placeholder: "Enter district",
          required: true,
          validation: "required",
          gridCols: "md:col-span-1",
        },
        {
          name: "state",
          label: "State",
          type: "text",
          placeholder: "Enter state",
          required: true,
          validation: "required",
          gridCols: "md:col-span-1",
        },
        {
          name: "pincode",
          label: "Pincode",
          type: "text",
          placeholder: "Enter 6-digit pincode",
          required: true,
          validation: "pincode",
          maxLength: 6,
          pattern: "[0-9]{6}",
          gridCols: "md:col-span-1",
        },
        {
          name: "latitude",
          label: "Latitude (Optional)",
          type: "number",
          placeholder: "e.g., 19.0760",
          required: false,
          validation: "latitude",
          step: "any",
          gridCols: "md:col-span-1",
        },
        {
          name: "longitude",
          label: "Longitude (Optional)",
          type: "number",
          placeholder: "e.g., 72.8777",
          required: false,
          validation: "longitude",
          step: "any",
          gridCols: "md:col-span-1",
        },
      ],
    },
    {
      id: "business_details",
      title: "Business Details",
      icon: "CreditCard",
      gradient: "from-orange-500 to-red-600",
      fields: [
        {
          name: "businessEmail",
          label: "Business Email",
          type: "email",
          placeholder: "business@example.com",
          required: true,
          validation: "email",
          gridCols: "lg:col-span-1",
        },
        {
          name: "website",
          label: "Website URL",
          type: "url",
          placeholder: "https://yourwebsite.com",
          required: false,
          validation: "url",
          gridCols: "lg:col-span-1",
        },
        {
          name: "establishedYear",
          label: "Established Year",
          type: "number",
          placeholder: "e.g., 2020",
          required: false,
          validation: "year",
          min: 1900,
          max: new Date().getFullYear(),
          gridCols: "md:col-span-1",
        },
        {
          name: "avgCostForTwo",
          label: "Average Cost for Two (₹)",
          type: "number",
          placeholder: "e.g., 800",
          required: false,
          validation: "positiveNumber",
          min: 0,
          gridCols: "md:col-span-1",
        },
        {
          name: "seatingCapacity",
          label: "Seating Capacity",
          type: "number",
          placeholder: "e.g., 50",
          required: false,
          validation: "positiveNumber",
          min: 0,
          gridCols: "md:col-span-1",
        },
        {
          name: "parkingAvailable",
          label: "Parking Available",
          type: "select",
          placeholder: "Select parking availability",
          required: false,
          validation: "",
          options: [
            { value: "", label: "Select Option" },
            { value: "yes", label: "Yes" },
            { value: "no", label: "No" },
            { value: "limited", label: "Limited" },
          ],
          gridCols: "md:col-span-1",
        },
      ],
    },
    {
      id: "operating_hours",
      title: "Operating Hours",
      icon: "Clock",
      gradient: "from-blue-500 to-cyan-600",
      fields: [
        {
          name: "operatingDays",
          label: "Operating Days",
          type: "checkbox-group",
          required: true,
          validation: "required",
          options: [
            { value: "monday", label: "Monday" },
            { value: "tuesday", label: "Tuesday" },
            { value: "wednesday", label: "Wednesday" },
            { value: "thursday", label: "Thursday" },
            { value: "friday", label: "Friday" },
            { value: "saturday", label: "Saturday" },
            { value: "sunday", label: "Sunday" },
          ],
          gridCols: "lg:col-span-2",
        },
        {
          name: "openingTime",
          label: "Opening Time",
          type: "time",
          placeholder: "Select opening time",
          required: true,
          validation: "required",
          gridCols: "md:col-span-1",
        },
        {
          name: "closingTime",
          label: "Closing Time",
          type: "time",
          placeholder: "Select closing time",
          required: true,
          validation: "required",
          gridCols: "md:col-span-1",
        },
        {
          name: "breakTime",
          label: "Break Time (Optional)",
          type: "text",
          placeholder: "e.g., 3:00 PM - 6:00 PM",
          required: false,
          validation: "",
          gridCols: "lg:col-span-2",
        },
      ],
    },
    {
      id: "services_features",
      title: "Services & Features",
      icon: "Star",
      gradient: "from-pink-500 to-rose-600",
      fields: [
        {
          name: "services",
          label: "Services Offered",
          type: "checkbox-group",
          required: false,
          validation: "",
          options: [
            { value: "dine_in", label: "Dine In" },
            { value: "takeaway", label: "Takeaway" },
            { value: "home_delivery", label: "Home Delivery" },
            { value: "catering", label: "Catering" },
            { value: "buffet", label: "Buffet" },
            { value: "outdoor_seating", label: "Outdoor Seating" },
            { value: "private_dining", label: "Private Dining" },
            { value: "live_music", label: "Live Music" },
            { value: "wifi", label: "Free WiFi" },
            { value: "ac", label: "Air Conditioned" },
            { value: "card_accepted", label: "Card Accepted" },
            { value: "wheelchair_accessible", label: "Wheelchair Accessible" },
          ],
          gridCols: "lg:col-span-2",
        },
        {
          name: "specialFeatures",
          label: "Special Features",
          type: "textarea",
          placeholder:
            "Mention any special features, themes, or unique offerings",
          required: false,
          validation: "",
          rows: 3,
          gridCols: "lg:col-span-2",
        },
      ],
    },
    {
      id: "legal_compliance",
      title: "Legal & Compliance",
      icon: "FileText",
      gradient: "from-violet-500 to-purple-600",
      fields: [
        {
          name: "gstNumber",
          label: "GST Number",
          type: "text",
          placeholder: "Enter 15-digit GST number",
          required: false,
          validation: "gst",
          maxLength: 15,
          gridCols: "lg:col-span-1",
        },
        {
          name: "fssaiNumber",
          label: "FSSAI License Number",
          type: "text",
          placeholder: "Enter FSSAI license number",
          required: true,
          validation: "fssai",
          maxLength: 14,
          gridCols: "lg:col-span-1",
        },
        {
          name: "panNumber",
          label: "PAN Number",
          type: "text",
          placeholder: "Enter 10-digit PAN number",
          required: false,
          validation: "pan",
          maxLength: 10,
          style: "uppercase",
          gridCols: "md:col-span-1",
        },
        {
          name: "tradeLicense",
          label: "Trade License Number",
          type: "text",
          placeholder: "Enter trade license number",
          required: false,
          validation: "",
          gridCols: "md:col-span-1",
        },
        {
          name: "liquorLicense",
          label: "Liquor License (if applicable)",
          type: "text",
          placeholder: "Enter liquor license number",
          required: false,
          validation: "",
          gridCols: "lg:col-span-2",
        },
      ],
    },
    {
      id: "social_media",
      title: "Social Media & Marketing",
      icon: "Share2",
      gradient: "from-green-500 to-emerald-600",
      fields: [
        {
          name: "instagramHandle",
          label: "Instagram Handle",
          type: "text",
          placeholder: "@yourbusiness",
          required: false,
          validation: "instagram",
          gridCols: "md:col-span-1",
        },
        {
          name: "facebookPage",
          label: "Facebook Page",
          type: "url",
          placeholder: "https://facebook.com/yourpage",
          required: false,
          validation: "url",
          gridCols: "md:col-span-1",
        },
        {
          name: "googleMapsLink",
          label: "Google Maps Link",
          type: "url",
          placeholder: "https://maps.google.com/...",
          required: false,
          validation: "url",
          gridCols: "lg:col-span-2",
        },
        {
          name: "zomatoLink",
          label: "Zomato Profile",
          type: "url",
          placeholder: "https://zomato.com/...",
          required: false,
          validation: "url",
          gridCols: "md:col-span-1",
        },
        {
          name: "swiggyLink",
          label: "Swiggy Profile",
          type: "url",
          placeholder: "https://swiggy.com/...",
          required: false,
          validation: "url",
          gridCols: "md:col-span-1",
        },
      ],
    },
  ],
};
