export const hotelFormConfig = {
  sections: [
    {
      id: "basic",
      title: "Basic Information",
      icon: "Building",
      gradient: "from-indigo-500 to-purple-600",
      fields: [
        {
          name: "businessName",
          label: "Business Name",
          type: "text",
          placeholder: "Enter your business name",
          required: true,
          validation: "businessName",
          gridCols: "lg:col-span-1",
        },
        {
          name: "businessType",
          label: "Business Type",
          type: "select",
          placeholder: "Select business type",
          required: true,
          validation: "required",
          options: [
            { value: "restaurant", label: "Restaurant" },
            { value: "hotel", label: "Hotel" },
            { value: "cafe", label: "Cafe" },
            { value: "dhaba", label: "Dhaba" },
            { value: "bar", label: "Bar" },
            { value: "fast_food", label: "Fast Food" },
            { value: "fine_dining", label: "Fine Dining" },
            { value: "food_truck", label: "Food Truck" },
            { value: "catering", label: "Catering Service" },
          ],
          gridCols: "lg:col-span-1",
        },
        {
          name: "primaryContact",
          label: "Primary Contact Number",
          type: "tel",
          placeholder: "Enter 10-digit contact number",
          required: true,
          validation: "contact",
          maxLength: 10,
          gridCols: "lg:col-span-1",
        },
        {
          name: "alternateContact",
          label: "Alternate Contact Number",
          type: "tel",
          placeholder: "Enter alternate contact (optional)",
          required: false,
          validation: "contactOptional",
          maxLength: 10,
          gridCols: "lg:col-span-1",
        },
        {
          name: "isActive",
          label: "Active",
          type: "select",
          placeholder: "Select Status",
          required: true,
          validation: "required",
          options: [
            { value: "active", label: "Active" },
            { value: "in_active", label: "In Active" },
          ],
          gridCols: "lg:col-span-1",
        },
      ],
    },
    {
      id: "location",
      title: "Location Information",
      icon: "MapPin",
      gradient: "from-emerald-500 to-teal-600",
      fields: [
        {
          name: "address",
          label: "Complete Address",
          type: "textarea",
          placeholder: "Enter complete business address",
          required: true,
          validation: "required",
          rows: 2,
          gridCols: "lg:col-span-2",
        },
        {
          name: "area",
          label: "Area/Locality",
          type: "text",
          placeholder: "Enter area or locality",
          required: true,
          validation: "required",
          gridCols: "lg:col-span-1",
        },
        {
          name: "landmark",
          label: "Landmark",
          type: "text",
          placeholder: "Enter nearby landmark",
          required: false,
          validation: "",
          gridCols: "lg:col-span-1",
        },
        {
          name: "city",
          label: "City",
          type: "text",
          placeholder: "Enter city",
          required: true,
          validation: "required",
          gridCols: "md:col-span-1",
        },
        {
          name: "district",
          label: "District",
          type: "text",
          placeholder: "Enter district",
          required: true,
          validation: "required",
          gridCols: "md:col-span-1",
        },
        {
          name: "state",
          label: "State",
          type: "text",
          placeholder: "Enter state",
          required: true,
          validation: "required",
          gridCols: "md:col-span-1",
        },
        {
          name: "country",
          label: "Country",
          type: "text",
          placeholder: "Enter Country",
          required: true,
          validation: "required",
          gridCols: "md:col-span-1",
        },
        {
          name: "pincode",
          label: "Pincode",
          type: "text",
          placeholder: "Enter 6-digit pincode",
          required: true,
          validation: "pincode",
          maxLength: 6,
          pattern: "[0-9]{6}",
          gridCols: "md:col-span-1",
        },
      ],
    },
    {
      id: "business_details",
      title: "Business Details",
      icon: "CreditCard",
      gradient: "from-orange-500 to-red-600",
      fields: [
        {
          name: "businessEmail",
          label: "Business Email",
          type: "email",
          placeholder: "business@example.com",
          required: true,
          validation: "email",
          gridCols: "lg:col-span-1",
        },
        {
          name: "website",
          label: "Website URL",
          type: "url",
          placeholder: "https://yourwebsite.com",
          required: false,
          validation: "url",
          gridCols: "lg:col-span-1",
        },
      ],
    },
    {
      id: "social_media",
      title: "Social Media & Marketing",
      icon: "Share2",
      gradient: "from-green-500 to-emerald-600",
      fields: [
        {
          name: "instagramHandle",
          label: "Instagram Handle",
          type: "text",
          placeholder: "@yourbusiness",
          required: false,
          validation: "instagram",
          gridCols: "md:col-span-1",
        },
        {
          name: "facebookPage",
          label: "Facebook Page",
          type: "url",
          placeholder: "https://facebook.com/yourpage",
          required: false,
          validation: "url",
          gridCols: "md:col-span-1",
        },
        {
          name: "googleMapsLink",
          label: "Google Maps Link",
          type: "url",
          placeholder: "https://maps.google.com/...",
          required: false,
          validation: "url",
          gridCols: "lg:col-span-2",
        },
        {
          name: "zomatoLink",
          label: "Zomato Profile",
          type: "url",
          placeholder: "https://zomato.com/...",
          required: false,
          validation: "url",
          gridCols: "md:col-span-1",
        },
        {
          name: "swiggyLink",
          label: "Swiggy Profile",
          type: "url",
          placeholder: "https://swiggy.com/...",
          required: false,
          validation: "url",
          gridCols: "md:col-span-1",
        },
      ],
    },
  ],
};
