import {
  DollarSign,
  Tag,
  FileText,
  ChefHat,
  Star,
  Utensils,
  Leaf,
  AlertCircle,
} from "lucide-react";

// Configuration object for form sections and fields
export const FORM_CONFIG = {
  sections: [
    {
      id: "basic",
      title: "Basic Information",
      icon: FileText,
      bgColor: "blue",
      fields: [
        {
          name: "menuName",
          label: "Menu Name",
          type: "text",
          required: true,
          placeholder: "e.g., Butter Chicken, Margherita Pizza",
          colSpan: 2,
        },
        {
          name: "menuContent",
          label: "Description",
          type: "textarea",
          required: true,
          placeholder:
            "Describe the dish, ingredients, and what makes it special...",
          rows: 3,
          colSpan: 2,
        },
        {
          name: "ingredients",
          label: "Key Ingredients",
          type: "text",
          placeholder: "e.g., Chicken, Tomatoes, Onions, Spices",
          colSpan: 2,
        },
        {
          name: "menuCookingTime",
          label: "Cooking Time (mins)",
          type: "number",
          required: true,
          placeholder: "25",
          min: "1",
        },
        {
          name: "servingSize",
          label: "Serves",
          type: "number",
          placeholder: "1",
          min: "1",
        },
      ],
    },
    {
      id: "pricing",
      title: "Pricing & Timing",
      icon: DollarSign,
      bgColor: "green",
      fields: [
        {
          name: "menuPrice",
          label: "Base Price (₹)",
          type: "number",
          required: true,
          placeholder: "199",
          min: "0",
          step: "0.01",
        },
        {
          name: "discount",
          label: "Discount (%)",
          type: "number",
          placeholder: "10",
          min: "0",
          max: "100",
        },
        {
          name: "finalPrice",
          label: "Final Price (₹)",
          type: "text",
          readonly: true,
          placeholder: "Auto-calculated",
        },

        {
          name: "calories",
          label: "Calories (kcal)",
          type: "number",
          placeholder: "450",
          min: "0",
        },
      ],
    },
    {
      id: "categories",
      title: "Categories & Classification",
      icon: Tag,
      bgColor: "purple",
      fields: [
        {
          name: "mainCategory",
          label: "Main Category",
          type: "select",
          options: "mainCategories",
        },
        {
          name: "menuCategory",
          label: "Menu Category",
          type: "select",
          required: true,
          options: "categories",
        },
        {
          name: "categoryType",
          label: "Category Type",
          type: "select",
          required: true,
          options: [
            { value: "veg", label: "🥬 Vegetarian" },
            { value: "nonveg", label: "🍖 Non-Vegetarian" },
          ],
        },
        {
          name: "mealType",
          label: "Meal Type",
          type: "select",
          options: "mealTypes",
        },
        {
          name: "spiceLevel",
          label: "Spice Level",
          type: "select",
          options: "spiceLevels",
        },
        
      ],
    },
    {
      id: "preparation",
      title: "Preparation Details",
      icon: Utensils,
      bgColor: "orange",
      fields: [
        {
          name: "preparationMethod",
          label: "Preparation Method",
          type: "select",
          options: "preparationMethods",
        },
        
        {
          name: "availability",
          label: "Availability",
          type: "select",
          options: [
            { value: "Available", label: "✅ Available" },
            { value: "Not Available", label: "❌ Not Available" },
          ],
        },
        {
          name: "cuisineType",
          label: "Cuisine Type",
          type: "select",
          options: "cuisineTypes",
        },
        {
          name: "tasteProfile",
          label: "Taste Profile ",
          type: "select",
          options: "tasteProfiles",
        },
        {
          name: "texture",
          label: "Texture",
          type: "select",
          options: "textures",
        },
        {
          name: "cookingStyle",
          label: "Cooking Style",
          type: "select",
          options: "cookingStyles",
        },
      ],
    },
    {
      id: "nutrition",
      title: "Nutritional Information",
      icon: Star,
      bgColor: "yellow",
      fields: [
        {
          name: "nutritionalInfo.protein",
          label: "Protein (g)",
          type: "number",
          placeholder: "25",
          min: "0",
        },
        {
          name: "nutritionalInfo.carbs",
          label: "Carbs (g)",
          type: "number",
          placeholder: "40",
          min: "0",
        },
        {
          name: "nutritionalInfo.fat",
          label: "Fat (g)",
          type: "number",
          placeholder: "15",
          min: "0",
        },
        {
          name: "nutritionalInfo.fiber",
          label: "Fiber (g)",
          type: "number",
          placeholder: "5",
          min: "0",
        },
      ],
    },
    {
      id: "features",
      title: "Special Features",
      icon: Leaf,
      bgColor: "red",
      fields: [
        {
          name: "chefSpecial",
          label: "Chef's Special",
          type: "checkbox",
          icon: ChefHat,
          iconColor: "orange",
        },
        {
          name: "isPopular",
          label: "Popular",
          type: "checkbox",
          icon: Star,
          iconColor: "yellow",
        },

        {
          name: "isRecommended",
          label: "Recommended",
          type: "checkbox",
          icon: AlertCircle,
          iconColor: "blue",
        },

        {
          name: "isMostOrdered",
          label: "Most Ordered",
          type: "checkbox",
          icon: AlertCircle,
          iconColor: "blue",
        },
        {
          name: "isSeasonal",
          label: "Seasonal",
          type: "checkbox",
          icon: AlertCircle,
          iconColor: "blue",
        },

        {
          name: "isLimitedEdition",
          label: "Limited Edition",
          type: "checkbox",
          icon: AlertCircle,
          iconColor: "blue",
        },
      ],
    },
    {
      id: "Dietary",
      title: "Dietary Info",
      icon: Leaf,
      bgColor: "orange",
      fields: [
        {
          name: "isVegan",
          label: "Vegan",
          type: "checkbox",
          icon: Leaf,
          iconColor: "green",
        },
        {
          name: "isGlutenFree",
          label: "Gluten Free",
          type: "checkbox",
          icon: AlertCircle,
          iconColor: "blue",
        },

        {
          name: "isSugarFree",
          label: "Sugar Free",
          type: "checkbox",
          icon: AlertCircle,
          iconColor: "blue",
        },

        {
          name: "isOrganic",
          label: "Organic",
          type: "checkbox",
          icon: AlertCircle,
          iconColor: "blue",
        },
        {
          name: "isHighProtein",
          label: "High Protein",
          type: "checkbox",
          icon: AlertCircle,
          iconColor: "blue",
        },
        {
          name: "isLactoseFree",
          label: "Lactose Free",
          type: "checkbox",
          icon: AlertCircle,
          iconColor: "blue",
        },
        {
          name: "isJainFriendly",
          label: "Jain Friendly",
          type: "checkbox",
          icon: AlertCircle,
          iconColor: "blue",
        },
        {
          name: "isKidsFriendly",
          label: "Kids Friendly ",
          type: "checkbox",
          icon: AlertCircle,
          iconColor: "blue",
        },
        {
          name: "isBeverageAlcoholic",
          label: "Beverage Alcoholic",
          type: "checkbox",
          icon: AlertCircle,
          iconColor: "blue",
        },

        {
          name: "allergens",
          label: "Contains Allergens",
          type: "multiselect",
          options: "allergenOptions",
          colSpan: 2,
        },
      ],
    },
  ],
};

// Special categories configuration
export const specialCategories = [
  {
    name: "chefSpecial",
    label: "Chef's Special",
    icon: ChefHat,
    iconColor: "text-orange-500",
    bgColor: "bg-orange-50",
    borderColor: "border-orange-200",
    activeColor: "bg-orange-500",
  },
  {
    name: "isPopular",
    label: "Popular",
    icon: Star,
    iconColor: "text-yellow-500",
    bgColor: "bg-yellow-50",
    borderColor: "border-yellow-200",
    activeColor: "bg-yellow-500",
  },
  {
    name: "isVegan",
    label: "Vegan",
    icon: Leaf,
    iconColor: "text-green-500",
    bgColor: "bg-green-50",
    borderColor: "border-green-200",
    activeColor: "bg-green-500",
  },
  {
    name: "isGlutenFree",
    label: "Gluten Free",
    icon: AlertCircle,
    iconColor: "text-blue-500",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-200",
    activeColor: "bg-blue-500",
  },
  {
    name: "isRecommended",
    label: "Recommended",
    icon: AlertCircle,
    iconColor: "text-purple-500",
    bgColor: "bg-purple-50",
    borderColor: "border-purple-200",
    activeColor: "bg-purple-500",
  },
  {
    name: "isSugarFree",
    label: "Sugar Free",
    icon: AlertCircle,
    iconColor: "text-pink-500",
    bgColor: "bg-pink-50",
    borderColor: "border-pink-200",
    activeColor: "bg-pink-500",
  },
  {
    name: "isMostOrdered",
    label: "Most Ordered",
    icon: AlertCircle,
    iconColor: "text-red-500",
    bgColor: "bg-red-50",
    borderColor: "border-red-200",
    activeColor: "bg-red-500",
  },
  {
    name: "isSeasonal",
    label: "Seasonal",
    icon: AlertCircle,
    iconColor: "text-emerald-500",
    bgColor: "bg-emerald-50",
    borderColor: "border-emerald-200",
    activeColor: "bg-emerald-500",
  },
  {
    name: "isLimitedEdition",
    label: "Limited Edition",
    icon: AlertCircle,
    iconColor: "text-indigo-500",
    bgColor: "bg-indigo-50",
    borderColor: "border-indigo-200",
    activeColor: "bg-indigo-500",
  },
  {
    name: "isOrganic",
    label: "Organic",
    icon: AlertCircle,
    iconColor: "text-lime-500",
    bgColor: "bg-lime-50",
    borderColor: "border-lime-200",
    activeColor: "bg-lime-500",
  },
  {
    name: "isHighProtein",
    label: "High Protein",
    icon: AlertCircle,
    iconColor: "text-teal-500",
    bgColor: "bg-teal-50",
    borderColor: "border-teal-200",
    activeColor: "bg-teal-500",
  },
  {
    name: "isLactoseFree",
    label: "Lactose Free",
    icon: AlertCircle,
    iconColor: "text-cyan-500",
    bgColor: "bg-cyan-50",
    borderColor: "border-cyan-200",
    activeColor: "bg-cyan-500",
  },
  {
    name: "isJainFriendly",
    label: "Jain Friendly",
    icon: AlertCircle,
    iconColor: "text-amber-500",
    bgColor: "bg-amber-50",
    borderColor: "border-amber-200",
    activeColor: "bg-amber-500",
  },
  {
    name: "isKidsFriendly",
    label: "Kids Friendly",
    icon: AlertCircle,
    iconColor: "text-rose-500",
    bgColor: "bg-rose-50",
    borderColor: "border-rose-200",
    activeColor: "bg-rose-500",
  },
  {
    name: "isBeverageAlcoholic",
    label: "Alcoholic",
    icon: AlertCircle,
    iconColor: "text-violet-500",
    bgColor: "bg-violet-50",
    borderColor: "border-violet-200",
    activeColor: "bg-violet-500",
  },
];
