// Enhanced color theme configuration
export const COLOR_THEMES = {
  green: {
    bg: "bg-green-500",
    bgGradient: "bg-gradient-to-br from-green-400 to-green-600",
    textPrimary: "text-green-600",
    textSecondary: "text-green-800",
    border: "border-green-200",
    shadow: "shadow-green-100",
    hoverShadow: "hover:shadow-green-200/50",
    focusRing: "focus:ring-green-500",
  },
  blue: {
    bg: "bg-blue-500",
    bgGradient: "bg-gradient-to-br from-blue-400 to-blue-600",
    textPrimary: "text-blue-600",
    textSecondary: "text-blue-800",
    border: "border-blue-200",
    shadow: "shadow-blue-100",
    hoverShadow: "hover:shadow-blue-200/50",
    focusRing: "focus:ring-blue-500",
  },
  red: {
    bg: "bg-red-500",
    bgGradient: "bg-gradient-to-br from-red-400 to-red-600",
    textPrimary: "text-red-600",
    textSecondary: "text-red-800",
    border: "border-red-200",
    shadow: "shadow-red-100",
    hoverShadow: "hover:shadow-red-200/50",
    focusRing: "focus:ring-red-500",
  },
  orange: {
    bg: "bg-orange-500",
    bgGradient: "bg-gradient-to-br from-orange-400 to-orange-600",
    textPrimary: "text-orange-600",
    textSecondary: "text-orange-800",
    border: "border-orange-200",
    shadow: "shadow-orange-100",
    hoverShadow: "hover:shadow-orange-200/50",
    focusRing: "focus:ring-orange-500",
  },
  purple: {
    bg: "bg-purple-500",
    bgGradient: "bg-gradient-to-br from-purple-400 to-purple-600",
    textPrimary: "text-purple-600",
    textSecondary: "text-purple-800",
    border: "border-purple-200",
    shadow: "shadow-purple-100",
    hoverShadow: "hover:shadow-purple-200/50",
    focusRing: "focus:ring-purple-500",
  },
  yellow: {
    bg: "bg-yellow-500",
    bgGradient: "bg-gradient-to-br from-yellow-400 to-yellow-600",
    textPrimary: "text-yellow-600",
    textSecondary: "text-yellow-800",
    border: "border-yellow-200",
    shadow: "shadow-yellow-100",
    hoverShadow: "hover:shadow-yellow-200/50",
    focusRing: "focus:ring-yellow-500",
  },
  teal: {
    bg: "bg-teal-500",
    bgGradient: "bg-gradient-to-br from-teal-400 to-teal-600",
    textPrimary: "text-teal-600",
    textSecondary: "text-teal-800",
    border: "border-teal-200",
    shadow: "shadow-teal-100",
    hoverShadow: "hover:shadow-teal-200/50",
    focusRing: "focus:ring-teal-500",
  },
};

export const getColorClasses = (colorName) => {
  const colorMap = {
    blue: "bg-blue-100 text-blue-600",
    green: "bg-green-100 text-green-600",
    red: "bg-red-100 text-red-600",
    yellow: "bg-yellow-100 text-yellow-600",
    purple: "bg-purple-100 text-purple-600",
    indigo: "bg-indigo-100 text-indigo-600",
    pink: "bg-pink-100 text-pink-600",
    gray: "bg-gray-100 text-gray-600",
    orange: "bg-orange-100 text-orange-600",
    teal: "bg-teal-100 text-teal-600",
  };
  return colorMap[colorName] || "bg-gray-100 text-gray-600";
};
