// Color theme configuration for QuickInfoCard
export const QUICK_INFO_COLOR_THEMES = {
  blue: {
    bg: "bg-gradient-to-r from-blue-50 to-blue-100",
    border: "border-blue-200",
    iconColor: "text-blue-600",
    labelColor: "text-blue-600",
    valueColor: "text-blue-800",
    shadowHover: "hover:shadow-blue-200/50",
    ringFocus: "focus:ring-blue-500",
  },
  orange: {
    bg: "bg-gradient-to-r from-orange-50 to-orange-100",
    border: "border-orange-200",
    iconColor: "text-orange-600",
    labelColor: "text-orange-600",
    valueColor: "text-orange-800",
    shadowHover: "hover:shadow-orange-200/50",
    ringFocus: "focus:ring-orange-500",
  },
  red: {
    bg: "bg-gradient-to-r from-red-50 to-red-100",
    border: "border-red-200",
    iconColor: "text-red-600",
    labelColor: "text-red-600",
    valueColor: "text-red-800",
    shadowHover: "hover:shadow-red-200/50",
    ringFocus: "focus:ring-red-500",
  },
  green: {
    bg: "bg-gradient-to-r from-green-50 to-green-100",
    border: "border-green-200",
    iconColor: "text-green-600",
    labelColor: "text-green-600",
    valueColor: "text-green-800",
    shadowHover: "hover:shadow-green-200/50",
    ringFocus: "focus:ring-green-500",
  },
  purple: {
    bg: "bg-gradient-to-r from-purple-50 to-purple-100",
    border: "border-purple-200",
    iconColor: "text-purple-600",
    labelColor: "text-purple-600",
    valueColor: "text-purple-800",
    shadowHover: "hover:shadow-purple-200/50",
    ringFocus: "focus:ring-purple-500",
  },
  gray: {
    bg: "bg-gradient-to-r from-gray-50 to-gray-100",
    border: "border-gray-200",
    iconColor: "text-gray-600",
    labelColor: "text-gray-600",
    valueColor: "text-gray-800",
    shadowHover: "hover:shadow-gray-200/50",
    ringFocus: "focus:ring-gray-500",
  },
  yellow: {
    bg: "bg-gradient-to-r from-yellow-50 to-yellow-100",
    border: "border-yellow-200",
    iconColor: "text-yellow-600",
    labelColor: "text-yellow-600",
    valueColor: "text-yellow-800",
    shadowHover: "hover:shadow-yellow-200/50",
    ringFocus: "focus:ring-yellow-500",
  },
  indigo: {
    bg: "bg-gradient-to-r from-indigo-50 to-indigo-100",
    border: "border-indigo-200",
    iconColor: "text-indigo-600",
    labelColor: "text-indigo-600",
    valueColor: "text-indigo-800",
    shadowHover: "hover:shadow-indigo-200/50",
    ringFocus: "focus:ring-indigo-500",
  },
};
